export {Slider1 as ScreenSlider1} from "./Slider1"
export {Slider2 as ScreenSlider2} from "./Slider2"
export {Login as ScreenLogin} from "./Login"
export {Cadastrar as ScreenCadastrar} from "./Cadastrar"
export {Perfil as SecreenPerfil} from "./Perfil"
export {CameraScreen as SreenCamera} from "./Camera"
export {LocationScreen as SreenLocation} from "./Location"
export { Acelerometro as ScreenAcelerometer } from "./Acelerometro"